### PR TITLE
moved all modifications of database to setUp and tearDown functions

### PR DESCRIPTION
**Pull request by tdamsma**

### CODE REVIEW

**Comment by Pegase745** [comment]
@tdamsma yep I thought of it afterwards. You were faster :)

**Comment by tdamsma** [comment]
anyways, it doesn't solve the main issue, cause 2/3 tests are failing with no reason. Could you try a rebuild?

**Comment by tdamsma** [comment]
Ideas for work around: 
 - place sqlite db on disk instead of in memory, and properly delete it.
 - use a proper db backend (postgres of mysql), with added benefit of being able to actually test
   - nulls ordering
   - regex searching

**Comment by Pegase745** [comment]
i'll setup the postgres yeah

**Comment by Pegase745** [comment]
@tdamsma tell me when it's ok to merge in my branch

**Comment by tdamsma** [comment]
@Pegase745 I think that (except for db errors) the tests should be ok now. So now would be ok

**Pull request merged**
