### PR TITLE
Update Flask example

### PR DESCRIPTION
**Pull request by grakic**
Resolves issue #70

### CODE REVIEW

**Comment by tdamsma** [comment]
Great work, do you think it would be worth it to also expand the flask example for to cover all cases the pyramid example does?

**Comment by Pegase745** [comment]
Great work indeed, thanks !

**Comment by tdamsma** [comment]
Also solves https://github.com/Pegase745/sqlalchemy-datatables/issues/74

**Comment by grakic** [comment]
@tdamsma It would be great, but I do not have time for it now

**Comment by Pegase745** [comment]
let's merge that as it is, and will update that in a next iteration

**Comment by Pegase745** [comment]
Fixes #70 #74

**Pull request merged**
