### PR TITLE
allow filter based on row data

### PR DESCRIPTION
**Pull request by louking**
* new parameter filterarg
* filterarg = 'cell' is default with filter=f(cell) as in 0.2.1
* filterarg = 'row' allows filter=f(row) for more complex filtering
* fixes https://github.com/Pegase745/sqlalchemy-datatables/issues/38

### CODE REVIEW

**Comment by Pegase745** [comment]
still a difference with #41 ? or you created a new PR from this branch ?

**Comment by louking** [comment]
I created #41 from this branch. This feature can be taken separately. Note I did not look at unit tests when I built this.

**Comment by Pegase745** [comment]
yep same problem with format I guess ;)

**Comment by Pegase745** [comment]
rebase onto master, as I added a quickfix earlier. And if you want I can merge this one, and let you enhance #41 . that's ok with you?

**Comment by louking** [comment]
are you asking me to rebase before you take this one?

yes you can wait on #41 until I improve it

**Comment by louking** [comment]
should be ready for you now

**Comment by Pegase745** [comment]
merged it. thanks. 

when you have time, could you possibly unit test `fitlerarg` before we pass onto the regex problems ? :)

**Comment by louking** [comment]
will try to do today. now I have travis installed on my fork. thanks for allowing me to use sqlalchemy-datatables as my tutorial repo ;)

**Comment by Pegase745** [comment]
No worries !

**Pull request merged**
